version: '3'
services:
  client:
    image: 'amirl1086/complex-client'
    mem_limit: 128m
    hostname: client
    container_name: client
  server:
    image: 'amirl1086/complex-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
    container_name: server
  worker:
    image: 'amirl1086/complex-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    container_name: worker
  nginx:
    image: 'amirl1086/complex-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
    container_name: nginx
